logging.level.root=${LOG_LEVEL:WARN}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}
contact.phone=1234567890
contact.email=qa@gmail.com
contact.address=Taiwan  