logging.level.root=${LOG_LEVEL:ERROR}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}
contact.phone=9876543210
contact.email=prod@gmail.com
contact.address=Canada