spring.application.name=BackEnd
# 「自動配置的詳細報告」+ 額外 debug log
#debug=true
# console 的日志输出格式 顏色
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
